### ISSUE TITLE
Neo4j stuck at " Attempting to connect to the other cluster members before continuing..." in K* Pod

### ISSUE THREAD

**Issue by ghost** [mneedham/neo4j-kubernetes#4]
Neo4j stuck at " Attempting to connect to the other cluster members before continuing..." in K* Pod

Please let me know, where I a missing
Pod Log:

2017-10-04T05:22:19.869450675Z Starting Neo4j.
2017-10-04T05:22:20.700879487Z 2017-10-04 05:22:20.699+0000 INFO  ======== Neo4j 3.2.3 ========
2017-10-04T05:22:20.741715691Z 2017-10-04 05:22:20.741+0000 INFO  Starting...
2017-10-04T05:22:22.69240081Z 2017-10-04 05:22:22.692+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2017-10-04T05:22:22.720298001Z 2017-10-04 05:22:22.720+0000 INFO  Initiating metrics...
2017-10-04T05:22:22.871594391Z 2017-10-04 05:22:22.871+0000 INFO  Resolved initial host 'neo4j.default.svc.cluster.local:5000' to []
2017-10-04T05:22:22.923101349Z 2017-10-04 05:22:22.922+0000 INFO  My connection info: [
2017-10-04T05:22:22.923128826Z 	Discovery:   listen=0.0.0.0:5000, advertised=neo4jdev-0.neo4jdev.default.svc.cluster.local:5000,
2017-10-04T05:22:22.923133033Z 	Transaction: listen=0.0.0.0:6000, advertised=neo4jdev-0.neo4jdev.default.svc.cluster.local:6000, 
2017-10-04T05:22:22.923145831Z 	Raft:        listen=0.0.0.0:7000, advertised=neo4jdev-0.neo4jdev.default.svc.cluster.local:7000, 
2017-10-04T05:22:22.923150015Z 	Client Connector Addresses: bolt://neo4jdev-0.neo4jdev.default.svc.cluster.local:7687,http://neo4jdev-0.neo4jdev.default.svc.cluster.local:7474,https://neo4jdev-0.neo4jdev.default.svc.cluster.local:7473
2017-10-04T05:22:22.92315428Z ]
2017-10-04T05:22:22.928242549Z 2017-10-04 05:22:22.927+0000 INFO  Discovering cluster with initial members: [neo4j.default.svc.cluster.local:5000]
2017-10-04T05:22:22.930790799Z 2017-10-04 05:22:22.930+0000 INFO  Attempting to connect to the other cluster members before continuing...
2017-10-09T06:32:19.459209874Z 2017-10-09 06:32:19.459+0000 INFO  Attempting to connect to the other cluster members before continuing...
2017-10-09T06:37:52.502700794Z 2017-10-09 06:37:52.502+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@24ca395c' was successfully initialized, but failed to start. Please see the attached cause exception "Failed to join a cluster with members {clusterId=null, bootstrappable=false, coreMembers={}}. Another member should have published a clusterId but none was detected. Please restart the cluster.". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@24ca395c' was successfully initialized, but failed to start. Please see the attached cause exception "Failed to join a cluster with members {clusterId=null, bootstrappable=false, coreMembers={}}. Another member should have published a clusterId but none was detected. Please restart the cluster.".
2017-10-09T06:37:52.502732862Z org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@24ca395c' was successfully initialized, but failed to start. Please see the attached cause exception "Failed to join a cluster with members {clusterId=null, bootstrappable=false, coreMembers={}}. Another member should have published a clusterId but none was detected. Please restart the cluster.".
2017-10-09T06:37:52.502738551Z 	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
2017-10-09T06:37:52.502743026Z 	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:215)
2017-10-09T06:37:52.502746483Z 	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:107)
2017-10-09T06:37:52.502749847Z 	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:80)
2017-10-09T06:37:52.502753303Z 	at org.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:32)
2017-10-09T06:37:52.502756715Z Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@24ca395c' was successfully initialized, but failed to start. Please see the attached cause exception "Failed to join a cluster with members {clusterId=null, bootstrappable=false, coreMembers={}}. Another member should have published a clusterId but none was detected. Please restart the cluster.".
2017-10-09T06:37:52.502760685Z 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
2017-10-09T06:37:52.50276361Z 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
2017-10-09T06:37:52.502766645Z 	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:207)
2017-10-09T06:37:52.502769662Z 	... 3 more
2017-10-09T06:37:52.502780903Z Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
2017-10-09T06:37:52.502784384Z 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:209)
2017-10-09T06:37:52.502787208Z 	at org.neo4j.causalclustering.core.CoreGraphDatabase.<init>(CoreGraphDatabase.java:49)
2017-10-09T06:37:52.502790312Z 	at org.neo4j.causalclustering.core.CoreGraphDatabase.<init>(CoreGraphDatabase.java:41)
2017-10-09T06:37:52.502793357Z 	at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$2(EnterpriseNeoServer.java:80)
2017-10-09T06:37:52.502796239Z 	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
2017-10-09T06:37:52.502799Z 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
2017-10-09T06:37:52.502801894Z 	... 5 more
2017-10-09T06:37:52.502804988Z Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.causalclustering.core.state.CoreLife@20a2ffd8' was successfully initialized, but failed to start. Please see the attached cause exception "Failed to join a cluster with members {clusterId=null, bootstrappable=false, coreMembers={}}. Another member should have published a clusterId but none was detected. Please restart the cluster.".
2017-10-09T06:37:52.502808499Z 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
2017-10-09T06:37:52.502811242Z 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
2017-10-09T06:37:52.502813941Z 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:205)
2017-10-09T06:37:52.502816756Z 	... 10 more
2017-10-09T06:37:52.502819813Z Caused by: java.util.concurrent.TimeoutException: Failed to join a cluster with members {clusterId=null, bootstrappable=false, coreMembers={}}. Another member should have published a clusterId but none was detected. Please restart the cluster.
2017-10-09T06:37:52.502823721Z 	at org.neo4j.causalclustering.identity.ClusterBinder.bindToCluster(ClusterBinder.java:110)
2017-10-09T06:37:52.502826532Z 	at org.neo4j.causalclustering.core.state.CoreLife.start(CoreLife.java:67)
2017-10-09T06:37:52.502839713Z 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
2017-10-09T06:37:52.502842616Z 	... 12 more
2017-10-09T06:37:52.503707776Z 2017-10-09 06:37:52.503+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by mshekhar-mE** [comment]
@nandakishore96 were you able to solve this?

**Comment by mshekhar-mE** [comment]
I'm getting similar error on starting a node in neo 3.2.4

**Comment by tech-mint** [comment]
try `nslookup {{ address of your discovery headless service }}` and report the result
